### ISSUE TITLE
Issue with live reloading when saving via neovim

### ISSUE THREAD

**Issue by megalithic** [wolfgangrittner/keepgoing#1]
Hi there!

Love the idea of this gem!

I've run into an issue with neovim, though, and I think I've seen similar issues with JS/CSS live-reloading things, too; but couldn't find the places i've come across previously.

So, basically the issue is, a `:w` (saving of the file to disk) fails to trigger a reload from `keepgoing`.

Have you heard of/run into anything similar?

**Comment by megalithic** [comment]
@wolfgangrittner - just curious if you've hit this before

**Comment by wolfgangrittner** [comment]
Hey @megalithic, glad you like `keepgoing`!

I've not run into this, sorry. There's probably also not really something `keepgoing` could do about it. It uses [guard](https://github.com/guard/guard), which in turn relies on the [listen](https://github.com/guard/listen) gem for detecting file changes.

Now if you are having trouble with `keepgoing` detecting file changes, chances are this is some issue with `listen` and you're most probably not the only one running into those issues, because `listen` is used by a number of other gems.
There are a couple of (closed) issues referencing vim on [listen's](https://github.com/guard/listen) issue tracker. Maybe there's one that fits what you are seeing?
